CREATE TABLE IF NOT EXISTS silver.rcbrequisicoes
(
    "CDFIL" VARCHAR,
    "NRRQU" VARCHAR,
    "ITEMID" VARCHAR,
    "TPRCB" VARCHAR,
    "VRRCB" NUMERIC,
    "DTOPE" DATE,
    "VRTXA" NUMERIC,
    "VRDSC" NUMERIC,
    "VRTRC" NUMERIC,
    "ALICM" NUMERIC,
    "BCICM" NUMERIC,
    "VRICM" NUMERIC,
    "PRUNILIQ" NUMERIC,
    "CDPIS" VARCHAR,
    "CDSITPIS" VARCHAR,
    "BCPIS" NUMERIC,
    "ALPIS" NUMERIC,
    "VRPIS" NUMERIC,
    "CDCOFINS" VARCHAR,
    "CDSITCOFINS" VARCHAR,
    "BCCOFINS" NUMERIC,
    "ALCOFINS" NUMERIC,
    "VRCOFINS" NUMERIC
);

INSERT INTO silver.rcbrequisicoes (
    "CDFIL", "NRRQU", "ITEMID", "TPRCB", "VRRCB", "DTOPE", "VRTXA", "VRDSC", "VRTRC", "ALICM",
    "BCICM", "VRICM", "PRUNILIQ", "CDPIS", "CDSITPIS", "BCPIS", "ALPIS", "VRPIS", "CDCOFINS",
    "CDSITCOFINS", "BCCOFINS", "ALCOFINS", "VRCOFINS"
)
SELECT 
    "CDFIL", "NRRQU", "ITEMID", "TPRCB", 
    CAST("VRRCB" AS NUMERIC), 
    CAST("DTOPE" AS DATE), 
    CAST("VRTXA" AS NUMERIC), 
    CAST("VRDSC" AS NUMERIC), 
    CAST("VRTRC" AS NUMERIC), 
    CAST("ALICM" AS NUMERIC), 
    CAST("BCICM" AS NUMERIC), 
    CAST("VRICM" AS NUMERIC), 
    CAST("PRUNILIQ" AS NUMERIC), 
    "CDPIS", 
    "CDSITPIS", 
    CAST("BCPIS" AS NUMERIC), 
    CAST("ALPIS" AS NUMERIC), 
    CAST("VRPIS" AS NUMERIC), 
    "CDCOFINS", 
    "CDSITCOFINS", 
    CAST("BCCOFINS" AS NUMERIC), 
    CAST("ALCOFINS" AS NUMERIC), 
    CAST("VRCOFINS" AS NUMERIC)
FROM temporary."FC17100"
WHERE NOT EXISTS (
    SELECT 1 
    FROM silver.rcbrequisicoes 
    WHERE silver.rcbrequisicoes."CDFIL" = temporary."FC17100"."CDFIL"
    AND silver.rcbrequisicoes."NRRQU" = temporary."FC17100"."NRRQU"
    AND silver.rcbrequisicoes."ITEMID" = temporary."FC17100"."ITEMID"
);
