
-----Insert na tabela silver clientes---------
INSERT INTO silver.clientes (
    "CDCLI", "CDFIL", "TPCLI", "NRCNPJ", "NRINSCR", "OERG", "TPSEX", "NOMECLI", "DTNAS", "LCNAS", "UFNAS",
    "CDRACACOR", "ECIVIL", "PROFIS", "DTCAD", "NOMEPAI", "NOMEMAE", "NOMECONJ", "INDFUMA", "INDCAFE", "INDALCO",
    "TPSANGUE", "CDOCUP", "OCENDCOR", "EMAIL", "EMAIL2", "HPAGE", "PTDSC", "PTTXA", "OBSERV", "OBSER", "OBSERTER",
    "FLAGENV", "INDCHA", "INDREFRI", "INDBALA", "INDCHOCO", "CDPOT", "OBSPOT", "PTDSCV", "PTDSCD", "UFRG", "TPDOC",
    "DTALT", "NRCARTAO", "CLCLI", "INDSMS", "OCENDERENTREGA", "NRSUFRAMA", "INDISENTOICMS", "TEMPLATE", "CDINDICACAO",
    "REGISTROCLIENTE", "INDMONITORA", "DTREV", "NRINSCRM", "INDDEFVISUAL", "INDEMAIL", "DTALTSYNC", "HRALTSYNC",
    "DELEXTERIOR", "RESP_RETENCION", "RESP_CREE", "INTEGRA_CARTERA", "CODRETENCION", "CODRETICA", "RETIVA", "AIU",
    "REGSIMP", "CDCONV", "DTHRALT", "HASHREG", "VERSAOPAF", "CDPERFILDEST", "INDAPLICATIVOMSG", "INDTELEFONE"
)
SELECT 
    "CDCLI", "CDFIL", "TPCLI", "NRCNPJ", "NRINSCR", "OERG", "TPSEX", "NOMECLI", 
    CAST(NULLIF("DTNAS", '') AS DATE), "LCNAS", "UFNAS",
    "CDRACACOR", "ECIVIL", "PROFIS", 
    CAST(NULLIF("DTCAD", '') AS DATE), "NOMEPAI", "NOMEMAE", "NOMECONJ", 
    CASE WHEN "INDFUMA" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDCAFE" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDALCO" = 'true' THEN TRUE ELSE FALSE END,
    "TPSANGUE", "CDOCUP", "OCENDCOR", "EMAIL", "EMAIL2", "HPAGE", "PTDSC", "PTTXA", "OBSERV", "OBSER", "OBSERTER",
    CASE WHEN "FLAGENV" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDCHA" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDREFRI" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDBALA" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDCHOCO" = 'true' THEN TRUE ELSE FALSE END,
    "CDPOT", "OBSPOT", "PTDSCV", "PTDSCD", "UFRG", "TPDOC",
    CAST(NULLIF("DTALT", '') AS DATE), "NRCARTAO", "CLCLI", 
    CASE WHEN "INDSMS" = 'true' THEN TRUE ELSE FALSE END,
    "OCENDERENTREGA", "NRSUFRAMA", 
    CASE WHEN "INDISENTOICMS" = 'true' THEN TRUE ELSE FALSE END,
    "TEMPLATE", "CDINDICACAO", "REGISTROCLIENTE",
    CASE WHEN "INDMONITORA" = 'true' THEN TRUE ELSE FALSE END,
    CAST(NULLIF("DTREV", '') AS DATE), "NRINSCRM",
    CASE WHEN "INDDEFVISUAL" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDEMAIL" = 'true' THEN TRUE ELSE FALSE END,
    CAST(NULLIF("DTALTSYNC", '') AS DATE), CAST(NULLIF("HRALTSYNC", '') AS TIME),
    CASE WHEN "DELEXTERIOR" = 'true' THEN TRUE ELSE FALSE END,
    "RESP_RETENCION", "RESP_CREE", "INTEGRA_CARTERA", "CODRETENCION", "CODRETICA", "RETIVA", "AIU",
    "REGSIMP", "CDCONV", 
    CAST(NULLIF("DTHRALT", '') AS TIMESTAMP), "HASHREG", "VERSAOPAF", "CDPERFILDEST",
    CASE WHEN "INDAPLICATIVOMSG" = 'true' THEN TRUE ELSE FALSE END,
    CASE WHEN "INDTELEFONE" = 'true' THEN TRUE ELSE FALSE END
FROM temporary."FC07000" src
WHERE NOT EXISTS (
    SELECT 1 
    FROM silver.clientes tgt 
    WHERE src."CDCLI" = tgt."CDCLI"
);






