CREATE TABLE IF NOT EXISTS silver.itensdasrequisicoes
(
    "CDFIL" varchar(50) COLLATE pg_catalog."default",
    "CDTML" varchar(50) COLLATE pg_catalog."default",
    "DTOPE" date,
    "OPERID" varchar(50) COLLATE pg_catalog."default",
    "NRCPM" varchar(50) COLLATE pg_catalog."default",
    "ITEMID" varchar(50) COLLATE pg_catalog."default",
    "VRTOT" numeric(10, 2),
    "TPDSC" varchar(50) COLLATE pg_catalog."default",
    "PTDSC" varchar(50) COLLATE pg_catalog."default",
    "VRDSC" numeric(10, 2),
    "TPOFR" varchar(50) COLLATE pg_catalog."default",
    "USERIDAUT" varchar(50) COLLATE pg_catalog."default",
    "CDTXA" varchar(50) COLLATE pg_catalog."default",
    "VRTXA" numeric(10, 2),
    "VRLIQ" numeric(10, 2),
    "TPPAG" varchar(50) COLLATE pg_catalog."default",
    "CDCON" varchar(50) COLLATE pg_catalog."default",
    "CDFUN" varchar(50) COLLATE pg_catalog."default",
    "CDCONEN" varchar(50) COLLATE pg_catalog."default",
    "CDFUNEN" varchar(50) COLLATE pg_catalog."default",
    "CDFILR" varchar(50) COLLATE pg_catalog."default",
    "NRRQU" varchar(50) COLLATE pg_catalog."default",
    "VRRCB" numeric(10, 2),
    "VRSDO" numeric(10, 2),
    "FLAGREL" boolean,
    "FLAGFCH" boolean,
    "FLAGLEZ" boolean,
    "FLAGBXA" boolean,
    "PTDSCG" varchar(50) COLLATE pg_catalog."default",
    "TPDSCG" varchar(50) COLLATE pg_catalog."default",
    "VRDSCG" numeric(10, 2),
    "CDTXAG" varchar(50) COLLATE pg_catalog."default",
    "VRTXAG" numeric(10, 2),
    "VRCXA" numeric(10, 2),
    "VRDIFCX" numeric(10, 2),
    "FLAGCST" boolean,
    "NRCPMF" varchar(50) COLLATE pg_catalog."default",
    "VRDIFCXRCB" numeric(10, 2),
    "HROPE" time without time zone,
    "DTVENC" date,
    "INDCONTINGENCIA" boolean,
    "NRCCF" varchar(50) COLLATE pg_catalog."default"
);

INSERT INTO silver.itensdasrequisicoes (
    "CDFIL", "CDTML", "DTOPE", "OPERID", "NRCPM", "ITEMID", "VRTOT", 
    "TPDSC", "PTDSC", "VRDSC", "TPOFR", "USERIDAUT", "CDTXA", "VRTXA", 
    "VRLIQ", "TPPAG", "CDCON", "CDFUN", "CDCONEN", "CDFUNEN", "CDFILR", 
    "NRRQU", "VRRCB", "VRSDO", "FLAGREL", "FLAGFCH", "FLAGLEZ", "FLAGBXA", 
    "PTDSCG", "TPDSCG", "VRDSCG", "CDTXAG", "VRTXAG", "VRCXA", "VRDIFCX", 
    "FLAGCST", "NRCPMF", "VRDIFCXRCB", "HROPE", "DTVENC", "INDCONTINGENCIA", 
    "NRCCF"
)
SELECT 
    "CDFIL", "CDTML", CAST("DTOPE" AS date), "OPERID", "NRCPM", "ITEMID", CAST("VRTOT" AS numeric(10, 2)), 
    "TPDSC", "PTDSC", CAST("VRDSC" AS numeric(10, 2)), "TPOFR", "USERIDAUT", "CDTXA", CAST("VRTXA" AS numeric(10, 2)), 
    CAST("VRLIQ" AS numeric(10, 2)), "TPPAG", "CDCON", "CDFUN", "CDCONEN", "CDFUNEN", "CDFILR", 
    "NRRQU", CAST("VRRCB" AS numeric(10, 2)), CAST("VRSDO" AS numeric(10, 2)), 
    CASE WHEN "FLAGREL" = 'true' THEN TRUE ELSE FALSE END, 
    CASE WHEN "FLAGFCH" = 'true' THEN TRUE ELSE FALSE END, 
    CASE WHEN "FLAGLEZ" = 'true' THEN TRUE ELSE FALSE END, 
    CASE WHEN "FLAGBXA" = 'true' THEN TRUE ELSE FALSE END, 
    "PTDSCG", "TPDSCG", CAST("VRDSCG" AS numeric(10, 2)), "CDTXAG", CAST("VRTXAG" AS numeric(10, 2)), 
    CAST("VRCXA" AS numeric(10, 2)), CAST("VRDIFCX" AS numeric(10, 2)), 
    CASE WHEN "FLAGCST" = 'true' THEN TRUE ELSE FALSE END, 
    "NRCPMF", CAST("VRDIFCXRCB" AS numeric(10, 2)), CAST("HROPE" AS time without time zone), 
    CAST("DTVENC" AS date), CASE WHEN "INDCONTINGENCIA" = 'true' THEN TRUE ELSE FALSE END, "NRCCF"
FROM temporary."FC31200";
