CREATE TABLE IF NOT EXISTS silver.componentesdasformulas
(
    "CDFIL" varchar(50),
    "NRRQU" varchar(50),
    "SERIER" varchar(50),
    "ITEMID" varchar(50),
    "TPCMP" varchar(5),
    "CDPRO" varchar(50),
    "CDPRIN" varchar(50),
    "DESCR" text,
    "QUANT" numeric,
    "UNIDA" varchar(10),
    "UNIHP" varchar(10),
    "VRCMP" numeric,
    "QTREAL" numeric,
    "INDQSP" varchar(5),
    "INDDOMAX" varchar(5),
    "INDELICMP" varchar(5),
    "INDASSOC" varchar(5),
    "INDQS" varchar(5),
    "VOLAPA" numeric,
    "PORTA" varchar(50),
    "QTPESA" numeric,
    "NRLOT" varchar(50),
    "CDFILE" varchar(50),
    "DTENTR" date,
    "DENSI" numeric,
    "DILUI" numeric,
    "FLAGPES" varchar(5),
    "CTLOT" varchar(50),
    "FLAGATU" varchar(5),
    "PRCUSTO" numeric,
    "CDSAC" varchar(50),
    "VRCMPORI" numeric,
    "QTREALORI" numeric,
    "VOLAPAORI" numeric,
    "QUANTHP" numeric,
    "UNIDAPRD" varchar(10),
    "INDVEICULO" varchar(5),
    "INDDILUI" varchar(5),
    "QTREALUNI" numeric,
    "CDPRINASS" varchar(50),
    "FLAGENV" varchar(5),
    "INDDOMIN" varchar(5),
    "TPASS" varchar(5),
    "TEOR" numeric,
    "CORGRID" integer,
    "EQUIV" numeric,
    "QTREALPSICO" numeric,
    "QTUTR" numeric,
    "QTUI" numeric,
    "QTBLH" numeric,
    "QTMLH" numeric,
    "QTMEQ" numeric,
    "QTUFC" numeric,
    "CDFILPRODPURO" varchar(50),
    "CDPROPRODPURO" varchar(50),
    "CTLOTPRODPURO" varchar(50),
    "NRLOTPRODPURO" varchar(50),
    "DILUIPRODPURO" numeric,
    "TEORPRODPURO" numeric,
    "INDDILUIDO" varchar(5),
    "NRNOTIF" varchar(50),
    "PRCOMPRA" numeric,
    "QTPERDA" numeric,
    "TPFORMAFARMA" varchar(50),
    "QTFCC" numeric,
    "QTMUF" numeric,
    "QTBUF" numeric,
    "INDESPFARM" varchar(5),
    "EXTERNOPERC" numeric,
    "INTERNOPERC" numeric,
    "QSPCAP" numeric
);

INSERT INTO silver."componentesdasformulas" (
    "CDFIL",
    "NRRQU",
    "SERIER",
    "ITEMID",
    "TPCMP",
    "CDPRO",
    "CDPRIN",
    "DESCR",
    "QUANT",
    "UNIDA",
    "UNIHP",
    "VRCMP",
    "QTREAL",
    "INDQSP",
    "INDDOMAX",
    "INDELICMP",
    "INDASSOC",
    "INDQS",
    "VOLAPA",
    "PORTA",
    "QTPESA",
    "NRLOT",
    "CDFILE",
    "DTENTR",
    "DENSI",
    "DILUI",
    "FLAGPES",
    "CTLOT",
    "FLAGATU",
    "PRCUSTO",
    "CDSAC",
    "VRCMPORI",
    "QTREALORI",
    "VOLAPAORI",
    "QUANTHP",
    "UNIDAPRD",
    "INDVEICULO",
    "INDDILUI",
    "QTREALUNI",
    "CDPRINASS",
    "FLAGENV",
    "INDDOMIN",
    "TPASS",
    "TEOR",
    "CORGRID",
    "EQUIV",
    "QTREALPSICO",
    "QTUTR",
    "QTUI",
    "QTBLH",
    "QTMLH",
    "QTMEQ",
    "QTUFC",
    "CDFILPRODPURO",
    "CDPROPRODPURO",
    "CTLOTPRODPURO",
    "NRLOTPRODPURO",
    "DILUIPRODPURO",
    "TEORPRODPURO",
    "INDDILUIDO",
    "NRNOTIF",
    "PRCOMPRA",
    "QTPERDA",
    "TPFORMAFARMA",
    "QTFCC",
    "QTMUF",
    "QTBUF",
    "INDESPFARM",
    "EXTERNOPERC",
    "INTERNOPERC",
    "QSPCAP"
)
SELECT
    "CDFIL",
    "NRRQU",
    "SERIER",
    "ITEMID",
    "TPCMP",
    "CDPRO",
    "CDPRIN",
    "DESCR",
    CAST(NULLIF("QUANT", '') AS numeric),
    "UNIDA",
    "UNIHP",
    CAST(NULLIF("VRCMP", '') AS numeric),
    CAST(NULLIF("QTREAL", '') AS numeric),
    "INDQSP",
    "INDDOMAX",
    "INDELICMP",
    "INDASSOC",
    "INDQS",
    CAST(NULLIF("VOLAPA", '') AS numeric),
    "PORTA",
    CAST(NULLIF("QTPESA", '') AS numeric),
    "NRLOT",
    "CDFILE",
    CAST(NULLIF("DTENTR", '') AS date),
    CAST(NULLIF("DENSI", '') AS numeric),
    CAST(NULLIF("DILUI", '') AS numeric),
    "FLAGPES",
    "CTLOT",
    "FLAGATU",
    CAST(NULLIF("PRCUSTO", '') AS numeric),
    "CDSAC",
    CAST(NULLIF("VRCMPORI", '') AS numeric),
    CAST(NULLIF("QTREALORI", '') AS numeric),
    CAST(NULLIF("VOLAPAORI", '') AS numeric),
    CAST(NULLIF("QUANTHP", '') AS numeric),
    "UNIDAPRD",
    "INDVEICULO",
    "INDDILUI",
    CAST(NULLIF("QTREALUNI", '') AS numeric),
    "CDPRINASS",
    "FLAGENV",
    "INDDOMIN",
    "TPASS",
    CAST(NULLIF("TEOR", '') AS numeric),
    CAST(FLOOR(NULLIF("CORGRID", '')::numeric) AS integer),
    CAST(NULLIF("EQUIV", '') AS numeric),
    CAST(NULLIF("QTREALPSICO", '') AS numeric),
    CAST(NULLIF("QTUTR", '') AS numeric),
    CAST(NULLIF("QTUI", '') AS numeric),
    CAST(NULLIF("QTBLH", '') AS numeric),
    CAST(NULLIF("QTMLH", '') AS numeric),
    CAST(NULLIF("QTMEQ", '') AS numeric),
    CAST(NULLIF("QTUFC", '') AS numeric),
    "CDFILPRODPURO",
    "CDPROPRODPURO",
    "CTLOTPRODPURO",
    "NRLOTPRODPURO",
    CAST(NULLIF("DILUIPRODPURO", '') AS numeric),
    CAST(NULLIF("TEORPRODPURO", '') AS numeric),
    "INDDILUIDO",
    "NRNOTIF",
    CAST(NULLIF("PRCOMPRA", '') AS numeric),
    CAST(NULLIF("QTPERDA", '') AS numeric),
    "TPFORMAFARMA",
    CAST(NULLIF("QTFCC", '') AS numeric),
    CAST(NULLIF("QTMUF", '') AS numeric),
    CAST(NULLIF("QTBUF", '') AS numeric),
    "INDESPFARM",
    CAST(NULLIF("EXTERNOPERC", '') AS numeric),
    CAST(NULLIF("INTERNOPERC", '') AS numeric),
    CAST(NULLIF("QSPCAP", '') AS numeric)
FROM temporary."FC12110" temp
WHERE NOT EXISTS (
    SELECT 1
    FROM silver."componentesdasformulas" s
    WHERE s."CDFIL" = temp."CDFIL"
      AND s."NRRQU" = temp."NRRQU"
      AND s."SERIER" = temp."SERIER"
      AND s."ITEMID" = temp."ITEMID"
);




