CREATE TABLE IF NOT EXISTS silver.produtos (
    produto_id SERIAL PRIMARY KEY,
    CDPRO INTEGER NOT NULL,
    DESCRPRD CHARACTER VARYING,
    DESCR CHARACTER VARYING,
    GRUPO CHARACTER VARYING,
    SETOR CHARACTER VARYING,
    UNIDA CHARACTER VARYING,
    SITUA CHARACTER VARYING,
    INDCIP CHARACTER VARYING,
    CURVA CHARACTER VARYING,
    LINHA CHARACTER VARYING
);

-- Inserir DADOS TABELA DIMENSAO PRODUTOS---

INSERT INTO silver.produtos (CDPRO, DESCRPRD, DESCR, GRUPO, SETOR, UNIDA, SITUA, INDCIP, CURVA, LINHA)
SELECT 
    CAST(temporary."FC03000"."CDPRO" AS INTEGER),          
    CAST(temporary."FC03000"."DESCRPRD" AS CHARACTER VARYING(20)), 
    CAST(temporary."FC03000"."DESCR" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."GRUPO" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."SETOR" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."UNIDA" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."SITUA" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."INDCIP" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."CURVA" AS CHARACTER VARYING),
    CAST(temporary."FC03000"."LINHA" AS CHARACTER VARYING)
FROM temporary."FC03000"
WHERE NOT EXISTS (
    SELECT 1 
    FROM silver.produtos 
    WHERE silver.produtos.CDPRO = CAST(temporary."FC03000"."CDPRO" AS INTEGER)
);

-- Atualizar os registros existentes com os valores das novas colunas
UPDATE silver.produtos
SET
    SITUA = temporary."FC03000"."SITUA",
    INDCIP = temporary."FC03000"."INDCIP",
    LINHA = temporary."FC03000"."LINHA"
FROM temporary."FC03000"
WHERE silver.produtos.CDPRO = CAST(temporary."FC03000"."CDPRO" AS INTEGER);

