CREATE VIEW gold.vw_combined_data AS
SELECT 
    v."CDFIL" AS v_CDFIL,
    v."DTOPE",
    v."OPERID",
    v."TPPAG",
    v."CDCON",
    v."CDFUN",
    v."CDCLI",
    v."CDCONRE",
    v."CDFUNRE",
    v."VRTOT" AS v_VRTOT,
    v."TPDSC",
    v."PTDSC",
    v."VRDSC" AS v_VRDSC,
    v."VRREC",
    v."VRRED",
    v."CDTXA",
    v."VRTXA",
    v."VRLIQ",
    v."VRTRC",
    v."QTTOT",
    v."VRCXA",
    v."VRRCB",
    v."CDSER",
    v."VRARC",
    v."NRPED" AS v_NRPED,
    v."NRNF",
    v."NRPEDIDO",
    v."VTQUANT",
    v."VTESPECIE",
    v."VTMARCA",
    v."VTNUMERO",
    v."DTEMI",
    v."DTSAI",
    v."HRSAI",
    v."NRINSCRST",
    v."VRCTA",
    v."VRFRE",
    v."VRTOTIPI",
    v."VRTOTPROD",
    v."NRNFCE",
    v."STATUSENOTAS",
    v."CDTML",
    v."ITEMID" AS v_ITEMID,
    v."CDFILR",
    v."CDPRO" AS v_CDPRO,
    v."QUANT" AS v_QUANT,
    v."PRUNI" AS v_PRUNI,
    v."VRDSCV",
    v."VRTXAV",
    v."CDIPI",
    v."PRCUSTO",
    v."PTLUCRO",
    v."DTPRESCR",
    v."QTPRESCR",
    v."PRCOMPRA",
    v."PRUNILIQ",
    v."NOMEPA",
    v."CDMVTO",
    v."ITEMIDH",
    c."CDFIL" AS c_CDFIL,
    c."TPCLI",
    c."NRCNPJ",
    c."NRINSCR",
    c."OERG",
    c."TPSEX",
    c."NOMECLI",
    c."DTNAS",
    c."LCNAS",
    c."UFNAS",
    c."CDRACACOR",
    c."ECIVIL",
    c."PROFIS",
    c."DTCAD",
    c."NOMEPAI",
    c."NOMEMAE",
    c."NOMECONJ",
    c."INDFUMA",
    c."INDCAFE",
    c."INDALCO",
    c."TPSANGUE",
    c."CDOCUP",
    c."OCENDCOR",
    c."EMAIL",
    c."EMAIL2",
    c."HPAGE",
    c."PTDSC" AS c_PTDSC,
    c."PTTXA",
    c."OBSERV",
    c."OBSER",
    c."OBSERTER",
    c."FLAGENV",
    c."INDCHA",
    c."INDREFRI",
    c."INDBALA",
    c."INDCHOCO",
    c."CDPOT",
    c."OBSPOT",
    c."PTDSCV" AS c_PTDSCV,
    c."PTDSCD",
    c."UFRG",
    c."TPDOC",
    c."DTALT",
    c."NRCARTAO",
    c."CLCLI",
    c."INDSMS",
    c."OCENDERENTREGA",
    c."NRSUFRAMA",
    c."INDISENTOICMS",
    c."TEMPLATE",
    c."CDINDICACAO",
    c."REGISTROCLIENTE",
    c."INDMONITORA",
    c."DTREV",
    c."NRINSCRM",
    c."INDDEFVISUAL",
    c."INDEMAIL",
    c."DTALTSYNC",
    c."HRALTSYNC",
    c."DELEXTERIOR",
    c."RESP_RETENCION",
    c."RESP_CREE",
    c."INTEGRA_CARTERA",
    c."CODRETENCION",
    c."CODRETICA",
    c."RETIVA",
    c."AIU",
    c."REGSIMP",
    c."CDCONV",
    c."DTHRALT",
    c."HASHREG",
    c."VERSAOPAF",
    c."CDPERFILDEST",
    c."INDAPLICATIVOMSG",
    c."INDTELEFONE",
    p.produto_id,
    p.cdpro AS p_cdpro,
    p.descrprd,
    p.descr,
    p.grupo,
    p.setor,
    p.unida AS p_unida,
    p.situa,
    p.indcip,
    p.curva,
    p.linha
FROM gold.combined_vendas v
LEFT JOIN gold.clientes c ON v."CDCLI" = c."CDCLI"
LEFT JOIN gold.produtos p ON v."CDPRO" = p.cdpro;
